<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
//$baseDir = dirname($vendorDir);

/*
return array(
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
);*/


return array(
    'Symfony\\Component\\Console\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/symfony/console')),
    'Doctrine\\ORM\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/orm/lib')),
    'Doctrine\\DBAL\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/dbal/lib')),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir .str_replace("/" ,DIRECTORY_SEPARATOR , '/doctrine/lexer/lib')),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/inflector/lib')),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/collections/lib')),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/cache/lib')),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/annotations/lib')),
    'Doctrine\\Common\\' => array($vendorDir . str_replace("/" ,DIRECTORY_SEPARATOR ,'/doctrine/common/lib')),
);

return $array1;
